// <auto-generated />
using System;
using AlimentaBem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlimentaBem.Migrations
{
    [DbContext(typeof(AlimentaBemContext))]
    [Migration("20260508144010_SecurityAndIndexes")]
    partial class SecurityAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlimentaBem.Src.Modules.Donation.Repository.Donation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("amountDonated")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("naturalPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("organizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("receivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("reviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("unavailableMessage")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("unavailableReason")
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("naturalPersonId");

                    b.HasIndex("organizationId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.NaturalPerson.Repository.NaturalPerson", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("age")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("birthdayDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("emailUser")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("gender")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("isPcd")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("skinColor")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("socialName")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("NaturalPersons");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Organization.Repository.Organization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("cnpj")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("type")
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.OrganizationRequirement.Repository.OrganizationRequirement", b =>
                {
                    b.Property<Guid>("id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("organizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("OrganizationRequirements");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.PasswordReset.Repository.PasswordResetToken", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("used")
                        .HasColumnType("boolean");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("token");

                    b.HasIndex("userId", "used");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Role.Repository.Role", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.User.Repository.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.UserOrganization.Repository.UserOrganization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("organizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("organizationId");

                    b.HasIndex("userId");

                    b.ToTable("UserOrganizations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Donation.Repository.Donation", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.NaturalPerson.Repository.NaturalPerson", "naturalPerson")
                        .WithMany("donations")
                        .HasForeignKey("naturalPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlimentaBem.Src.Modules.Organization.Repository.Organization", "organization")
                        .WithMany("donations")
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("naturalPerson");

                    b.Navigation("organization");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.NaturalPerson.Repository.NaturalPerson", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.User.Repository.User", "user")
                        .WithMany("naturalPersons")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.OrganizationRequirement.Repository.OrganizationRequirement", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.Organization.Repository.Organization", "organization")
                        .WithMany("OrganizationRequirements")
                        .HasForeignKey("id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Role.Repository.Role", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.User.Repository.User", "user")
                        .WithMany("roles")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.UserOrganization.Repository.UserOrganization", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.Organization.Repository.Organization", "organization")
                        .WithMany()
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlimentaBem.Src.Modules.User.Repository.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");

                    b.Navigation("user");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.NaturalPerson.Repository.NaturalPerson", b =>
                {
                    b.Navigation("donations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Organization.Repository.Organization", b =>
                {
                    b.Navigation("OrganizationRequirements");

                    b.Navigation("donations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.User.Repository.User", b =>
                {
                    b.Navigation("naturalPersons");

                    b.Navigation("roles");
                });
#pragma warning restore 612, 618
        }
    }
}
