// <auto-generated />
using System;
using AlimentaBem.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlimentaBem.Migrations
{
    [DbContext(typeof(AlimentaBemContext))]
    [Migration("20260423201256_DonationStatusFlow")]
    partial class DonationStatusFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlimentaBem.Src.Modules.Donation.Repository.Donation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("amountDonated")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("naturalPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("organizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("receivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("reviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unavailableMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unavailableReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("naturalPersonId");

                    b.HasIndex("organizationId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.NaturalPerson.Repository.NaturalPerson", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("birthdayDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("emailUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gender")
                        .HasColumnType("int");

                    b.Property<bool?>("isPcd")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("skinColor")
                        .HasColumnType("int");

                    b.Property<string>("socialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("NaturalPersons");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Organization.Repository.Organization", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.OrganizationRequirement.Repository.OrganizationRequirement", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("organizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.HasIndex("organizationId");

                    b.ToTable("OrganizationRequirements");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Role.Repository.Role", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("userId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.User.Repository.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("createdAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("deletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("updatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Donation.Repository.Donation", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.NaturalPerson.Repository.NaturalPerson", "naturalPerson")
                        .WithMany("donations")
                        .HasForeignKey("naturalPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlimentaBem.Src.Modules.Organization.Repository.Organization", "organization")
                        .WithMany("donations")
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("naturalPerson");

                    b.Navigation("organization");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.NaturalPerson.Repository.NaturalPerson", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.User.Repository.User", "user")
                        .WithMany("naturalPersons")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.OrganizationRequirement.Repository.OrganizationRequirement", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.Organization.Repository.Organization", "organization")
                        .WithMany("OrganizationRequirements")
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Role.Repository.Role", b =>
                {
                    b.HasOne("AlimentaBem.Src.Modules.User.Repository.User", "user")
                        .WithMany("roles")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.NaturalPerson.Repository.NaturalPerson", b =>
                {
                    b.Navigation("donations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.Organization.Repository.Organization", b =>
                {
                    b.Navigation("OrganizationRequirements");

                    b.Navigation("donations");
                });

            modelBuilder.Entity("AlimentaBem.Src.Modules.User.Repository.User", b =>
                {
                    b.Navigation("naturalPersons");

                    b.Navigation("roles");
                });
#pragma warning restore 612, 618
        }
    }
}
